name: MarvelCharacters
configs:
  Development Debug: debug
  Development Release: release
settings:
  configs:
    Development Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEVELDEBUG
    Development Release:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEVELRELEASE

options:
  bundleIdPrefix: com.mina
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "15.0"
#fileGroups:
#- project.yml
#- Configuration
#- Makefile
targets:
  MarvelCharacters:
    type: application
    platform: iOS
    sources: ["MarvelCharacters"]
    scheme:
      testTargets:
        - MarvelCharactersTests
      configVariants:
        - Development
    preBuildScripts:
      - name: "SwiftLint"
        script: |
                export PATH="$PATH:/opt/homebrew/bin"
                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi

    settings:
        base:
            INFOPLIST_FILE: MarvelCharacters/Info.plist
            PRODUCT_BUNDLE_IDENTIFIER: me.mina.EtisalatTask
            CODE_SIGN_STYLE: Automatic

  MarvelCharactersTests:
    type: bundle.unit-test
    platform: iOS
    sources: ["MarvelCharactersTests"]
    dependencies:
      - target: MarvelCharacters
    settings:
        base:
            PRODUCT_BUNDLE_IDENTIFIER: com.mina.EtisalatTaskTests

